name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for private repositories

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Install dependencies and deploy
      run: |
        sudo apt update
        sudo apt install python3-pip -y
        pip3 install -r requirements.txt

        cd /path/to/your/app
        git pull origin main  # or specific branch

        # Gunicorn command to start your Flask app
        gunicorn -b 0.0.0.0:80 app:app  # Replace with your Gunicorn command
